from colorama import Fore, Back, Style
import time
import os
os.system("clear")
print("")
print("")
time.sleep(1)
print(Fore.CYAN + "        █░░█ █▀▀▄ ░▀░ ▀█░█▀ █▀▀ █▀▀█ █▀▀ █▀▀█ █░░")
time.sleep(0.2)
print(Fore.CYAN + "        █░░█ █░░█ ▀█▀ ░█▄█░ █▀▀ █▄▄▀ ▀▀█ █▄▄█ █░░")
time.sleep(0.2)
print(Fore.CYAN + "        ░▀▀▀ ▀░░▀ ▀▀▀ ░░▀░░ ▀▀▀ ▀░▀▀ ▀▀▀ ▀░░▀ ▀▀▀")
print("")
print("")
time.sleep(2)
print(Fore.YELLOW + "            PUBG MOBILE ANTIBAN DEVELOPED BY")
time.sleep(1)
print(Fore.RED + "           ----------------------------------")
time.sleep(1)
print(Fore.CYAN + "             ╔═══╦╗─╔╦╗──╔═══╦╗─╔╦╗─╔╦═══╗")
print(Fore.CYAN + "             ║╔═╗║║─║║║──║╔═╗║║─║║║─║║╔═╗║")
print(Fore.CYAN + "             ║╚══╣║─║║║──║╚═╝║╚═╝║║─║║╚═╝║")
print(Fore.CYAN + "             ╚══╗║║─║║║─╔╣╔══╣╔═╗║║─║║╔╗╔╝")
print(Fore.CYAN + "             ║╚═╝║╚═╝║╚═╝║║──║║─║║╚═╝║║║╚╗")
print(Fore.CYAN + "             ╚═══╩═══╩═══╩╝──╚╝─╚╩═══╩╝╚═╝")
time.sleep(1)
print(Fore.RED + "           ----------------------------------")
time.sleep(1)
print(Fore.YELLOW + "            Telegram Channel :- @OnlySulphur")
time.sleep(1)

def get_menu_choice():
    def print_menu():       # Your menu design here
           print("")
           print(Fore.GREEN + "1: PUBG - GLOBAL ]>")
           print(Fore.GREEN + "2: PUBG - KOREAN  ]> ")
           print(Fore.GREEN + "3: PUBG - TAIWAN  ]> ")
           print(Fore.GREEN + "4: PUBG - VIETNAM ]>")
           print(Fore.GREEN + "5: TELEGRAM CHANNEL ]>")
           print(Fore.GREEN + "6: ABOUT PROJECT  ]>")   
           print(Fore.GREEN + "7: TURN OFF ANTIBAN/Exit ]>")   
           print("")
    loop = True
    
    while loop:          # While loop which will keep going until loop = False
        print_menu()    # Displays menu
        choice = input("----> ENTER YOUR REQUIRED OPTION :-  ")

        if choice == '1':
                  print("")
                  print("")
                  print("")
                  print(Fore.RED + "         --------------------------------------")
                  time.sleep(1)
                  print(Fore.MAGENTA + "         STARTING PUBG GLOBAL WITHOUT ANTICHEAT")
                  time.sleep(1)
                  print(Fore.RED + "         --------------------------------------")
                  print("")
                  os.system("su -c iptables --flush")
                  f = open("/proc/sys/fs/inotify/max_user_watches", "w")
                  f.write("8192")
                  f.close()
                  os.system("su -c rm -rf /data/data/com.tencent.ig/files  &> /dev/null")
                  os.system("su -c touch /data/data/com.tencent.ig/files")

                  os.system('su -c rm -rf /data/app/com.tencent.ig*/lib/arm*/{*Bug*,*arc*,*help*,*big*,*blb*,*npp*,*eng*,*zip*,*mast*} &>/dev/null ')
                  os.system('su -c am start -n com.tencent.ig/com.epicgames.ue4.SplashActivity &>/dev/null ')
                  time.sleep(5)
                  os.system('su -c rm -rf /storage/emulated/0/ADARSH &>/dev/null ')
                  os.system('mkdir /storage/emulated/0/ADARSH')

                  os.system('su -c mv /data/app/com.tencent.ig*/lib/arm*/libUE4.so /storage/emulated/0/ADARSH &>/dev/null')
                  os.system('su -c mv /data/app/com.tencent.ig*/lib/arm*/libtersafe.so /storage/emulated/0/ADARSH &>/dev/null')

                  os.system('su -c mv /storage/emulated/0/ADARSH/* /data/app/com.tencent.ig*/lib/arm* &>/dev/null')
                  os.system('su -c chmod 755 /data/app/com.tencent.ig*/lib/arm*/* &>/dev/null')
                  os.system('su -c chmod 664 /data/media/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/*.pak')
                  time.sleep(60)
                  os.system('su -c iptables -I INPUT -p tcp  --dport 20002 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 20002 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 20002 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 20002 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 17000 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 17000 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 17000 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 17000 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 20001 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 20001 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 20001 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 20001 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 20000 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 20000 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 20000 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 20000 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 18081 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 18081 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 18081 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 18081 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 10672 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 10672 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 10672 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 10672 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 10013 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 10013 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 10013 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 10013 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 10133 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 10133 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 10133 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 10133 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 60938 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 60938 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 10401 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 10401 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 35182 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 35182 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 38613 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 38613 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 39210 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 39210 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 49309 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 49309 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 54678 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 54678 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 31119 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 31119 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 53 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 53 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 56500 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 56500 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 37803 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 37803 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 35717 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 35717 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 34580 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 34580 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 54354 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 54354 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 33320 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 33320 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 20371 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 20371 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 8114 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 8114 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 20010 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 20010 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 48214 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 48214 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 42584 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 42584 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 39080 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 39080 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 37870 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 37870 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 45552 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 45552 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 39494 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 39494 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 18081 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 18081 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 17000 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 17000 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 9030 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 9030 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 8700 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 8700 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 9031 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 9031 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 3013 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 3013 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 18081 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 18081 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 15692 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 15692 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 20000 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 20000 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 20001 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 20001 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 10013 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 10013 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 11443 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 11443 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 10178 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 10178 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 20371 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 20371 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 8088 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 8088 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 8085 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 8085 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 8086 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 8086 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 10012 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 10012 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 20002 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 20002 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 17000 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 17000 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 443 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 443 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 9030 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 9030 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 8700 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 8700 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 9031 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 9031 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 3013 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 3013 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 8011 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 8011 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 18081 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 18081 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 15692 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 15692 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 20000 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 20000 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 20001 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 20001 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 10013 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 10013 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 11443 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 11443 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 10178 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 10178 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 20371 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 20371 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 8088 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 8088 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 8085 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 8085 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 8086 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 8086 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 10012 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 10012 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 20002 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 20002 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 60938 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 60938 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 10401 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 10401 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 35182 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 35182 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 38613 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 38613 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 39210 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 39210 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 49309 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 49309 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 54678 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 54678 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 31119 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 31119 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 53 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 53 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 56500 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 56500 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 37803 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 37803 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 35717 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 35717 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 34580 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 34580 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 54354 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 54354 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 33320 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 33320 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 20371 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 20371 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 8114 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 8114 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 20010 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 20010 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 48214 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 48214 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 42584 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 42584 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 39080 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 39080 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 37870 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 37870 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 45552 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 45552 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 39494 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 39494 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 18081 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 18081 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 443 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 443 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 443 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 443 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 443 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 443 -j DROP')

        elif choice == '2':
                  print("")
                  print("")
                  print("")
                  print(Fore.RED + "         --------------------------------------")
                  time.sleep(1)
                  print(Fore.MAGENTA + "         STARTING PUBG KOREA WITHOUT ANTICHEAT")
                  time.sleep(1)
                  print(Fore.RED + "         --------------------------------------")
                  print("")
                  os.system("su -c iptables --flush")
                  f = open("/proc/sys/fs/inotify/max_user_watches", "w")
                  f.write("8192")
                  f.close()
                  os.system("su -c rm -rf /data/data/com.pubg.krmobile/files  &> /dev/null")
                  os.system("su -c touch /data/data/com.pubg.krmobile/files")

                  os.system('su -c rm -rf /data/app/com.pubg.krmobile*/lib/arm*/{*Bug*,*arc*,*help*,*big*,*blb*,*npp*,*eng*,*zip*,*mast*} &>/dev/null ')
                  os.system('su -c am start -n com.pubg.krmobile/com.epicgames.ue4.SplashActivity &>/dev/null ')
                  time.sleep(5)
                  os.system('su -c rm -rf /storage/emulated/0/ADARSH &>/dev/null ')
                  os.system('mkdir /storage/emulated/0/ADARSH')

                  os.system('su -c mv /data/app/com.pubg.krmobile*/lib/arm*/libUE4.so /storage/emulated/0/ADARSH &>/dev/null')
                  os.system('su -c mv /data/app/com.pubg.krmobile*/lib/arm*/libtersafe.so /storage/emulated/0/ADARSH &>/dev/null')

                  os.system('su -c mv /storage/emulated/0/ADARSH/* /data/app/com.pubg.krmobile*/lib/arm* &>/dev/null')
                  os.system('su -c chmod 755 /data/app/com.pubg.krmobile*/lib/arm*/* &>/dev/null')
                  os.system('su -c chmod 664 /data/media/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/*.pak')
                  time.sleep(60)
                  os.system('su -c iptables -I INPUT -p tcp  --dport 20002 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 20002 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 20002 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 20002 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 17000 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 17000 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 17000 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 17000 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 20001 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 20001 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 20001 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 20001 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 20000 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 20000 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 20000 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 20000 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 18081 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 18081 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 18081 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 18081 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 10672 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 10672 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 10672 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 10672 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 10013 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 10013 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 10013 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 10013 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 10133 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 10133 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 10133 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 10133 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 60938 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 60938 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 10401 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 10401 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 35182 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 35182 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 38613 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 38613 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 39210 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 39210 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 49309 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 49309 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 54678 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 54678 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 31119 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 31119 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 53 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 53 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 56500 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 56500 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 37803 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 37803 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 35717 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 35717 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 34580 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 34580 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 54354 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 54354 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 33320 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 33320 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 20371 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 20371 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 8114 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 8114 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 20010 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 20010 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 48214 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 48214 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 42584 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 42584 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 39080 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 39080 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 37870 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 37870 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 45552 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 45552 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 39494 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 39494 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 18081 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 18081 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 17000 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 17000 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 9030 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 9030 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 8700 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 8700 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 9031 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 9031 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 3013 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 3013 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 18081 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 18081 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 15692 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 15692 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 20000 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 20000 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 20001 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 20001 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 10013 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 10013 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 11443 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 11443 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 10178 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 10178 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 20371 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 20371 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 8088 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 8088 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 8085 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 8085 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 8086 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 8086 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 10012 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 10012 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 20002 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 20002 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 17000 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 17000 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 443 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 443 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 9030 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 9030 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 8700 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 8700 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 9031 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 9031 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 3013 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 3013 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 8011 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 8011 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 18081 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 18081 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 15692 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 15692 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 20000 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 20000 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 20001 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 20001 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 10013 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 10013 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 11443 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 11443 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 10178 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 10178 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 20371 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 20371 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 8088 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 8088 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 8085 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 8085 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 8086 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 8086 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 10012 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 10012 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 20002 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 20002 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 60938 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 60938 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 10401 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 10401 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 35182 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 35182 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 38613 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 38613 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 39210 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 39210 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 49309 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 49309 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 54678 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 54678 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 31119 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 31119 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 53 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 53 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 56500 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 56500 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 37803 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 37803 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 35717 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 35717 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 34580 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 34580 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 54354 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 54354 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 33320 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 33320 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 20371 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 20371 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 8114 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 8114 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 20010 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 20010 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 48214 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 48214 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 42584 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 42584 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 39080 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 39080 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 37870 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 37870 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 45552 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 45552 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 39494 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 39494 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 18081 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 18081 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 443 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 443 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 443 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 443 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 443 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 443 -j DROP')
        elif choice == '3':
                  print("")
                  print("")
                  print("")
                  print(Fore.RED + "         --------------------------------------")
                  time.sleep(1)
                  print(Fore.MAGENTA + "         STARTING PUBG TAIWAN WITHOUT ANTICHEAT")
                  time.sleep(1)
                  print(Fore.RED + "         --------------------------------------")
                  print("")
                  os.system("su -c iptables --flush")
                  f = open("/proc/sys/fs/inotify/max_user_watches", "w")
                  f.write("8192")
                  f.close()
                  os.system("su -c rm -rf /data/data/com.rekoo.pubgm/files  &> /dev/null")
                  os.system("su -c touch /data/data/com.rekoo.pubgm/files")

                  os.system('su -c rm -rf /data/app/com.rekoo.pubgm*/lib/arm*/{*Bug*,*arc*,*help*,*big*,*blb*,*npp*,*eng*,*zip*,*mast*} &>/dev/null ')
                  os.system('su -c am start -n com.rekoo.pubgm/com.epicgames.ue4.SplashActivity &>/dev/null ')
                  time.sleep(5)
                  os.system('su -c rm -rf /storage/emulated/0/ADARSH &>/dev/null ')
                  os.system('mkdir /storage/emulated/0/ADARSH')

                  os.system('su -c mv /data/app/com.rekoo.pubgm*/lib/arm*/libUE4.so /storage/emulated/0/ADARSH &>/dev/null')
                  os.system('su -c mv /data/app/com.rekoo.pubgm*/lib/arm*/libtersafe.so /storage/emulated/0/ADARSH &>/dev/null')

                  os.system('su -c mv /storage/emulated/0/ADARSH/* /data/app/com.rekoo.pubgm*/lib/arm* &>/dev/null')
                  os.system('su -c chmod 755 /data/app/com.rekoo.pubgm*/lib/arm*/* &>/dev/null')
                  os.system('su -c chmod 664 /data/media/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/*.pak')
                  time.sleep(60)
                  os.system('su -c iptables -I INPUT -p tcp  --dport 20002 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 20002 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 20002 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 20002 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 17000 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 17000 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 17000 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 17000 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 20001 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 20001 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 20001 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 20001 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 20000 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 20000 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 20000 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 20000 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 18081 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 18081 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 18081 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 18081 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 10672 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 10672 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 10672 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 10672 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 10013 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 10013 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 10013 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 10013 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 10133 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 10133 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 10133 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 10133 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 60938 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 60938 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 10401 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 10401 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 35182 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 35182 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 38613 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 38613 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 39210 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 39210 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 49309 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 49309 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 54678 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 54678 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 31119 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 31119 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 53 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 53 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 56500 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 56500 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 37803 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 37803 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 35717 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 35717 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 34580 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 34580 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 54354 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 54354 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 33320 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 33320 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 20371 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 20371 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 8114 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 8114 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 20010 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 20010 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 48214 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 48214 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 42584 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 42584 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 39080 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 39080 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 37870 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 37870 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 45552 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 45552 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 39494 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 39494 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 18081 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 18081 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 17000 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 17000 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 9030 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 9030 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 8700 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 8700 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 9031 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 9031 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 3013 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 3013 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 18081 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 18081 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 15692 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 15692 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 20000 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 20000 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 20001 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 20001 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 10013 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 10013 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 11443 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 11443 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 10178 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 10178 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 20371 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 20371 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 8088 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 8088 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 8085 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 8085 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 8086 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 8086 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 10012 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 10012 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 20002 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 20002 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 17000 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 17000 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 443 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 443 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 9030 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 9030 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 8700 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 8700 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 9031 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 9031 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 3013 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 3013 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 8011 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 8011 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 18081 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 18081 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 15692 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 15692 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 20000 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 20000 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 20001 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 20001 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 10013 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 10013 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 11443 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 11443 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 10178 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 10178 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 20371 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 20371 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 8088 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 8088 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 8085 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 8085 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 8086 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 8086 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 10012 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 10012 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 20002 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 20002 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 60938 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 60938 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 10401 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 10401 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 35182 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 35182 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 38613 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 38613 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 39210 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 39210 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 49309 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 49309 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 54678 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 54678 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 31119 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 31119 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 53 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 53 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 56500 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 56500 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 37803 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 37803 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 35717 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 35717 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 34580 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 34580 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 54354 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 54354 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 33320 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 33320 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 20371 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 20371 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 8114 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 8114 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 20010 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 20010 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 48214 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 48214 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 42584 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 42584 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 39080 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 39080 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 37870 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 37870 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 45552 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 45552 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 39494 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 39494 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 18081 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 18081 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 443 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 443 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 443 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 443 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 443 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 443 -j DROP')
        elif choice == '4':
                  print("")
                  print("")
                  print("")
                  print(Fore.RED + "         --------------------------------------")
                  time.sleep(1)
                  print(Fore.MAGENTA + "         STARTING PUBG VIETNAM WITHOUT ANTICHEAT")
                  time.sleep(1)
                  print(Fore.RED + "         --------------------------------------")
                  print("")
                  os.system("su -c iptables --flush")
                  f = open("/proc/sys/fs/inotify/max_user_watches", "w")
                  f.write("8192")
                  f.close()
                  os.system("su -c rm -rf /data/data/com.vng.pubgmobile/files  &> /dev/null")
                  os.system("su -c touch /data/data/com.vng.pubgmobile/files")

                  os.system('su -c rm -rf /data/app/com.vng.pubgmobile*/lib/arm*/{*Bug*,*arc*,*help*,*big*,*blb*,*npp*,*eng*,*zip*,*mast*} &>/dev/null ')
                  os.system('su -c am start -n com.vng.pubgmobile/com.epicgames.ue4.SplashActivity &>/dev/null ')
                  time.sleep(5)
                  os.system('su -c rm -rf /storage/emulated/0/ADARSH &>/dev/null ')
                  os.system('mkdir /storage/emulated/0/ADARSH')

                  os.system('su -c mv /data/app/com.vng.pubgmobile*/lib/arm*/libUE4.so /storage/emulated/0/ADARSH &>/dev/null')
                  os.system('su -c mv /data/app/com.vng.pubgmobile*/lib/arm*/libtersafe.so /storage/emulated/0/ADARSH &>/dev/null')

                  os.system('su -c mv /storage/emulated/0/ADARSH/* /data/app/com.vng.pubgmobile*/lib/arm* &>/dev/null')
                  os.system('su -c chmod 755 /data/app/com.vng.pubgmobile*/lib/arm*/* &>/dev/null')
                  os.system('su -c chmod 664 /data/media/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/*.pak')
                  time.sleep(60)
                  os.system('su -c iptables -I INPUT -p tcp  --dport 20002 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 20002 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 20002 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 20002 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 17000 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 17000 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 17000 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 17000 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 20001 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 20001 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 20001 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 20001 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 20000 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 20000 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 20000 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 20000 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 18081 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 18081 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 18081 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 18081 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 10672 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 10672 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 10672 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 10672 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 10013 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 10013 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 10013 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 10013 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 10133 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 10133 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 10133 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 10133 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 60938 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 60938 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 10401 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 10401 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 35182 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 35182 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 38613 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 38613 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 39210 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 39210 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 49309 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 49309 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 54678 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 54678 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 31119 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 31119 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 53 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 53 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 56500 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 56500 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 37803 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 37803 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 35717 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 35717 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 34580 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 34580 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 54354 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 54354 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 33320 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 33320 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 20371 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 20371 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 8114 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 8114 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 20010 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 20010 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 48214 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 48214 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 42584 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 42584 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 39080 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 39080 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 37870 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 37870 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 45552 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 45552 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 39494 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 39494 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 18081 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 18081 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 17000 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 17000 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 9030 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 9030 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 8700 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 8700 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 9031 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 9031 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 3013 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 3013 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 18081 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 18081 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 15692 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 15692 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 20000 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 20000 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 20001 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 20001 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 10013 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 10013 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 11443 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 11443 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 10178 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 10178 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 20371 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 20371 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 8088 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 8088 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 8085 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 8085 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 8086 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 8086 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 10012 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 10012 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 20002 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 20002 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 17000 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 17000 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 443 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 443 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 9030 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 9030 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 8700 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 8700 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 9031 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 9031 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 3013 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 3013 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 8011 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 8011 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 18081 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 18081 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 15692 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 15692 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 20000 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 20000 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 20001 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 20001 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 10013 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 10013 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 11443 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 11443 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 10178 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 10178 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 20371 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 20371 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 8088 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 8088 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 8085 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 8085 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 8086 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 8086 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 10012 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 10012 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 20002 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 20002 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 60938 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 60938 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 10401 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 10401 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 35182 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 35182 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 38613 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 38613 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 39210 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 39210 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 49309 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 49309 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 54678 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 54678 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 31119 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 31119 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 53 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 53 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 56500 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 56500 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 37803 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 37803 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 35717 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 35717 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 34580 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 34580 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 54354 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 54354 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 33320 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 33320 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 20371 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 20371 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 8114 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 8114 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 20010 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 20010 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 48214 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 48214 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 42584 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 42584 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 39080 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 39080 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 37870 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 37870 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 45552 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 45552 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 39494 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 39494 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 18081 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 18081 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 443 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 443 -j DROP')
                  os.system('su -c iptables -I INPUT -p udp  --dport 443 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p udp  --dport 443 -j DROP')
                  os.system('su -c iptables -I INPUT -p tcp  --dport 443 -j DROP')
                  os.system('su -c iptables -I OUTPUT -p tcp  --dport 443 -j DROP')
        elif choice == '5':
                  print("")
                  print(Fore.CYAN + "Opening Telegram . . .")
                  print("")
                  time.sleep(2)
                  os.system("su -c am start -n org.telegram.messenger/org.telegram.ui.LaunchActivity https://t.me/onlysulphur  &> /dev/null")
                  
        elif choice == '6':
                  os.system("clear")
                  print("")
                  print("")
                  print(Fore.RED + "UNIVERSAL ANTIBAN is An Antiban Program Developed By Sulphur For Pubg Mobile Game.")
                  print("")
                  print(Fore.BLUE + "Its Features Are As Follows :-")

                  print(Fore.WHITE + "1. It Helps You To Use In Game Cheats/Hacks without Any Fear Of Getting Ban.")

                  print(Fore.WHITE + "2. It Supports All Android Versions & All Pubg Versions.")

                  print(Fore.WHITE + "3. No Memory Antiban is needed with this Antiban.")

                  print(Fore.WHITE + "4. Pubg will Never Gonna patch this method Of Antiban.")

                  print(Fore.WHITE + "5. It Is Easy to Use without any complicated process.")
 
        elif choice == '7':                  
                  os.system("clear")
                  os.system("su -c rm -rf /storage/emulated/0/.backups &>/dev/null   ")
                  os.system("su -c touch /storage/emulated/0/.backups &>/dev/null   ")
                  os.system("su -c chmod -R 000 /storage/emulated/0/.backups")
                  os.system("su -c iptables -P INPUT ACCEPT")
                  os.system("su -c iptables -P OUTPUT ACCEPT")
                  os.system("su -c iptables -P FORWARD ACCEPT")
                  os.system("su -c ip6tables -P INPUT ACCEPT")
                  os.system("su -c ip6tables -P OUTPUT ACCEPT")
                  os.system("su -c ip6tables -P FORWARD ACCEPT")
                  os.system("su -c iptables -F")
                  os.system("su -c iptables -t nat -F")
                  os.system("su -c iptables -t mangle -F")
                  os.system("su -c iptables -X")
                  os.system("su -c iptables --flush")
                  os.system("su -c rm -rf /data/media/0/Android/data/com.pubg.krmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames/*.json &>/dev/null   ")
                  os.system("su -c rm -rf /data/media/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames/*.json &>/dev/null   ")
                  os.system("su -c rm -rf /data/media/0/Android/data/com.vng.pubgmobile/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames/*.json &>/dev/null   ")
                  os.system("su -c rm -rf /data/media/0/Android/data/com.rekoo.pubgm/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames/*.json &>/dev/null   ")
                  os.system("su -c rm -rf /data/data/com.termux/files/usr/Adarsh.py &>/dev/null ")
                  print("")
                  print(Fore.MAGENTA + ".  ████████╗██╗░░██╗░█████╗░███╗░░██╗██╗░░██╗░██████╗")
                  print(Fore.MAGENTA + ".  ╚══██╔══╝██║░░██║██╔══██╗████╗░██║██║░██╔╝██╔════╝")
                  print(Fore.MAGENTA + "   ░░░██║░░░███████║███████║██╔██╗██║█████═╝░╚█████╗░")
                  print(Fore.MAGENTA + "   ░░░██║░░░██╔══██║██╔══██║██║╚████║██╔═██╗░░╚═══██╗")
                  print(Fore.MAGENTA + "   ░░░██║░░░██║░░██║██║░░██║██║░╚███║██║░╚██╗██████╔╝")
                  print(Fore.MAGENTA + "   ░░░╚═╝░░░╚═╝░░╚═╝╚═╝░░╚═╝╚═╝░░╚══╝╚═╝░░╚═╝╚═════╝░")
                  print("")
                  print("")
                  print(Fore.RED + " ---> ANTIBAN DEACTIVATED ")
                  print(Fore.RED + " ---> DONT FORGET TO SHARE THIS PROGRAM.")
                  print(Fore.RED + " ---> AND PLEASE PROVIDE US FEEDBACKS.")
                  print(Fore.RED + " ---> t.me/onlySulphur")
                  print("")
                  exit()
        else:
                print("")
            # Any inputs other than values 1-4 we print an error message
                input("You Can only Enter 1 to 7 Numbers, please enter any key to Try Again - ")
                return [int_choice, choice]


print(get_menu_choice())